// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqTrsRZAZzqvDcCspX-1cSjkZTFyd0A8E',
    appId: '1:1052806276671:android:f3087b0aaeb5bdd45eba8a',
    messagingSenderId: '1052806276671',
    projectId: 'ystyle-d0610',
    storageBucket: 'ystyle-d0610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYEqTu1_mENEsfjn8_W60BpxFF6B_IFs',
    appId: '1:1052806276671:ios:744e220a874222365eba8a',
    messagingSenderId: '1052806276671',
    projectId: 'ystyle-d0610',
    storageBucket: 'ystyle-d0610.appspot.com',
    androidClientId: '1052806276671-d6ul3ri4scc1rb373c7dho9deev8shgn.apps.googleusercontent.com',
    iosClientId: '1052806276671-ijate4bpdsc0vpcb2j79d6ui8rg6jsun.apps.googleusercontent.com',
    iosBundleId: 'com.itsyasirali.ystyle',
  );
}
